import express from "express";
import roleRouter from "./user/role.routes.js";
import permissionRouter from "./user/permissions.routes.js";
import userRouter from "./user/user.routes.js";
import resourceRouter from "./user/resource.routes.js";
import clientRouter from "./client/client.routes.js";
import contactRouter from "./client/contact.routes.js";
import suppliersRouter from "./suppliers/suppliers.routes.js";
import supplierContactsRouter from "./suppliers/supplierContacts.routes.js";
import inventoryRouter from "./inventory/inventory.routes.js";
import cabinetRouter from "./cabinet/cabinet.routes.js";
import auditRouter from "./audit/audit.routes.js";
import notificationRouter from "./notification/notification.routes.js";
import cabinetCategoriesRouter from "./cabinet/cabinetCategories.routes.js";
import cabinetSubcategoriesRouter from "./cabinet/cabinetSubcategories.routes.js";
import cabinetQuoteRouter from "./cabinet/cabinetMaterial.routes.js";
import priceBookRouter from "./suppliers/priceBook.routes.js";
import priceBookCategoryRouter from "./suppliers/priceBookCategory.routes.js";
import workerRouter from "./worker/worker.routes.js";
import projectRouter from "./project/project.routes.js";
import projectManagementRouter from "./project/projectManagement.routes.js";
import employeeRouter from "./employeeLeave/employeeLeave.routes.js";
import projectSetupRouter from "./project/projectSetup.routes.js";
import projectVariationRouter from "./project/projectVariation.routes.js";
import employeeTimeSheetRouter from "./humanResource/employeeTimeSheet.routes.js";
import noticeRouter from "./humanResource/notice.routes.js";
import employeeDocumentRouter from "./humanResource/employeeDocument.routes.js";
import jobSchedulingRouter from "./project/jobScheduling/jobScheduling.routes.js";
import projectKanbanRouter from "./project/jobScheduling/projectKanban.routes.js";
import projectGanttChartRouter from "./project/jobScheduling/projectGanttChart.routes.js";
import noteRouter from "./project/jobScheduling/note.routes.js";


const router = express.Router();

router.use('/role', roleRouter);
router.use('/permission', permissionRouter);
router.use('/user', userRouter);
router.use('/resource', resourceRouter);
router.use('/client', clientRouter);
router.use('/contact', contactRouter);
router.use('/suppliers', suppliersRouter);
router.use('/supplier-contacts', supplierContactsRouter);
router.use('/inventory', inventoryRouter);
router.use('/cabinet', cabinetRouter);
router.use('/audit', auditRouter);
router.use("/notification", notificationRouter)
router.use('/cabinet-categories', cabinetCategoriesRouter);
router.use('/cabinet-subcategories', cabinetSubcategoriesRouter);
router.use('/cabinet-quote', cabinetQuoteRouter);
router.use('/pricebook-categories', priceBookCategoryRouter);
router.use('/pricebook', priceBookRouter);
router.use('/workers', workerRouter);
router.use('/projects', projectRouter);
router.use('/project-management', projectManagementRouter);
router.use('/employee-leave', employeeRouter);
router.use('/project-setup', projectSetupRouter);
router.use('/project-variation', projectVariationRouter);
router.use("/employee-timesheet", employeeTimeSheetRouter);
router.use("/notices", noticeRouter);
router.use("/employee-document", employeeDocumentRouter);
router.use("/job-scheduling", jobSchedulingRouter);
router.use("/project-kanban", projectKanbanRouter);
router.use("/project-gantt-chart", projectGanttChartRouter);
router.use("/note", noteRouter);

export default router;
